var programList = [
    {
        programNo: '৭৭৪৯',
        programDate: '১৫/১২/২০২২',
        sendingPoint: 'চট্টগ্রাম বন্দর',
        recievingPoint: 'সিলেট সদর',
        noOfSlacks: '৩০০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'চাউল',
        programStatus: 'প্রেরিত', 
        programId: 1,
    },
    {
        programNo: '৭১৩৪৪৯',
        programDate: '০১/১০/২০২৩',
        sendingPoint: 'আশুগঞ্জ সাইলো',
        recievingPoint: 'হালিশহর সিএসডি',
        noOfSlacks: '৪৫০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'গম',
        programStatus: 'বিল করা হয়েছে', 
        programId: 2,
    },
    {
        programNo: '৭৭৪৯',
        programDate: '১৫/১২/২০২২',
        sendingPoint: 'চট্টগ্রাম বন্দর',
        recievingPoint: 'সিলেট সদর',
        noOfSlacks: '৩০০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'চাউল',
        programStatus: 'প্রেরিত', 
        programId: 3,
    },
    {
        programNo: '৭৭৪৯',
        programDate: '১৫/১২/২০২২',
        sendingPoint: 'চট্টগ্রাম বন্দর',
        recievingPoint: 'সিলেট সদর',
        noOfSlacks: '৩০০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'চাউল',
        programStatus: 'প্রেরিত', 
        programId: 4,
    },
    {
        programNo: '৭৭৪৯',
        programDate: '১৫/১২/২০২২',
        sendingPoint: 'চট্টগ্রাম বন্দর',
        recievingPoint: 'সিলেট সদর',
        noOfSlacks: '৩০০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'চাউল',
        programStatus: 'প্রেরিত', 
        programId: 5,
    },
    {
        programNo: '৭৭৪৯',
        programDate: '১৫/১২/২০২২',
        sendingPoint: 'চট্টগ্রাম বন্দর',
        recievingPoint: 'সিলেট সদর',
        noOfSlacks: '৩০০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'চাউল',
        programId: 6,
    },
    {
        programNo: '৭৭৪৯',
        programDate: '১৫/১২/২০২২',
        sendingPoint: 'চট্টগ্রাম বন্দর',
        recievingPoint: 'সিলেট সদর',
        noOfSlacks: '৩০০',
        sendingDate: '১৩/১২/২০২২',
        receivingDate: '১৩/১২/২০২২',
        comodity: 'চাউল',
        programId: 7,
    },
];

export default programList;